# General Jekyll Config
pygments: true
baseurl: /wordpress-on-gae/
lsi: false
exclude: [README.md, .gitignore]
markdown: kramdown

# Theme customization - please change from the defaults!
theme:
  name: Running Wordpress on Google App Engine

  # Color for top bar, links, etc
  highlight_color: '#c82986'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: aucor
    #bitbucket: 
    #stackexchange: 
    #stackoverflow: 
    twitter: aucor
    #facebook: 
    #tumblr: 
    #linkedin: 
    #gplus: 

  # Google Analytics key, leave blank to ignore
  #google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  #show_disclaimer: true
